language: python

before_install:
  - sudo apt-get install python3

sudo: required

python:
  - "3.5"

cache: pip

os: Linux

script: 
  - pytest

install:
  - python installer.py
  - pip install requests
  - pip install prettytable
  - pip install termcolor
  - cd tests

