ADHRIT:
  adhrit_slack_token: 'This slack token fetches the apk uploaded on to slack from the slack link provided on JIRA tickets, Also this same token is being used for slack-apk scanning.'
  jarvis_slack_tocken: ''
JIRA:
  adhrit_ip: ''
  keyword: ''
  project: SECAUTO
  slack_token: ''
  title: Adhrit - Android Security Suite Report
  token: 'echo -n example@mail.com:token | base64'
  url: https://dreamplug.atlassian.net